-- USE SAKILA DATABASE
USE sakila;

-- CHALLENGE 1: List the number of films per category
-- We need to join 'film_category' and 'category' to get the category names
SELECT c.name AS category_name, COUNT(fc.film_id) AS number_of_films
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
GROUP BY c.name
ORDER BY number_of_films DESC;

-- CHALLENGE 2: Retrieve the store ID, city, and country for each store
-- This requires joining 'store' -> 'address' -> 'city' -> 'country'
SELECT s.store_id, ci.city, co.country
FROM store s
JOIN address a ON s.address_id = a.address_id
JOIN city ci ON a.city_id = ci.city_id
JOIN country co ON ci.country_id = co.country_id;

-- CHALLENGE 3: Calculate the total revenue generated by each store in dollars
-- We join 'store' -> 'staff' -> 'payment' to sum the amounts
SELECT s.store_id, SUM(p.amount) AS total_revenue
FROM store s
JOIN staff st ON s.store_id = st.store_id
JOIN payment p ON st.staff_id = p.staff_id
GROUP BY s.store_id;

-- CHALLENGE 4: Determine the average running time of films for each category
-- We join 'film' -> 'film_category' -> 'category'
SELECT c.name AS category_name, ROUND(AVG(f.length), 2) AS average_running_time
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC;

-- BONUS CHALLENGE 5: Identify the film categories with the longest average running time
-- Using the same logic as above but filtering with HAVING or just observing the top of the sorted list
SELECT c.name AS category_name, ROUND(AVG(f.length), 2) AS average_running_time
FROM category c
JOIN film_category fc ON c.category_id = fc.category_id
JOIN film f ON fc.film_id = f.film_id
GROUP BY c.name
ORDER BY average_running_time DESC
LIMIT 5;

-- BONUS CHALLENGE 6: Display the top 10 most frequently rented movies
-- We join 'film' -> 'inventory' -> 'rental'
SELECT f.title, COUNT(r.rental_id) AS rental_count
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN rental r ON i.inventory_id = r.inventory_id
GROUP BY f.title
ORDER BY rental_count DESC
LIMIT 10;

-- BONUS CHALLENGE 7: Determine if "Academy Dinosaur" can be rented from Store 1
-- We check if the film exists in the inventory of store 1
SELECT f.title, s.store_id, COUNT(i.inventory_id) AS availability
FROM film f
JOIN inventory i ON f.film_id = i.film_id
JOIN store s ON i.store_id = s.store_id
WHERE f.title = 'ACADEMY DINOSAUR' AND s.store_id = 1
GROUP BY f.title, s.store_id;